from typing import Protocol, runtime_checkable

from ..schema import Candidate, ConsistencyReview, DirectorDecision, Narrative, ProjectInput, Prompts, Scene


@runtime_checkable
class PlanningAgentProtocol(Protocol):
    def run(self, project_input: ProjectInput) -> Narrative: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class StoryboardAgentProtocol(Protocol):
    def run(self, narrative: Narrative, project_input: ProjectInput) -> list[Scene]: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class PromptAgentProtocol(Protocol):
    def run(self, scene: Scene, feedback: str | None = None) -> Prompts: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class ImageAgentProtocol(Protocol):
    def run(self, prompts: Prompts, reference_image_urls: list[str] | None = None) -> Candidate: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class ImageEditAgentProtocol(Protocol):
    def run(self, candidate: Candidate, prompts: Prompts, feedback: str) -> Candidate: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class ReviewAgentProtocol(Protocol):
    def run(self, candidate: Candidate, prior_candidates: list[Candidate], prompts: Prompts) -> ConsistencyReview: ...
    def estimate_cost(self) -> float: ...


@runtime_checkable
class DirectorAgentProtocol(Protocol):
    def run(self, scene: Scene, review: ConsistencyReview) -> DirectorDecision: ...
    def estimate_cost(self) -> float: ...
